function val = J3vCR(~,~,Gpts4ref,n4e,s4e,averaging_coefficients,bubble_coefficients,volume_coefficients,area4e)

%% this function expresses J3vCR as a function of barycentric coordinates
% see "calculations_integrateJ3vCR.pdf" for derivation of the formulas

% define constants
alpha = sqrt(20 / 27) * (sqrt(7) + 1);
beta = sqrt(20 / 27) * 3 * sqrt(7);

%% represent J3vCR with barycentric coordinates
lambda2 = Gpts4ref(1);
lambda3 = Gpts4ref(2);
lambda1 = 1 - lambda2 - lambda3;

% a1*λ1 + a2*λ2 + a3*λ3
term1 = averaging_coefficients(n4e(:,1)) * lambda1 + ...
    averaging_coefficients(n4e(:,2)) * lambda2 + ...
    averaging_coefficients(n4e(:,3)) * lambda3;

% 6*(b1 λ2λ3 + b2 λ1λ3 + b3 λ1λ2)
term2 = 6 * (...
    bubble_coefficients(s4e(:,1)) * lambda2 * lambda3 + ...
    bubble_coefficients(s4e(:,2)) * lambda1 * lambda3 + ...
    bubble_coefficients(s4e(:,3)) * lambda1 * lambda2 ...
    );

% 27/√|T| λ1λ2λ3 [ α(c1+c2+c3) − β(c1λ1+c2λ2+c3λ3) ]
term3 = (27 ./ sqrt(area4e) * lambda1 * lambda2 * lambda3) .* ...
    (alpha * sum(volume_coefficients,2) - ...
    beta * ( ...
    volume_coefficients(:,1) * lambda1 + ...
    volume_coefficients(:,2) * lambda2 + ...
    volume_coefficients(:,3) * lambda3 ...
    )...
    );

val = term1 + term2 + term3;

end